v3: finalize low-hanging tasks

diff --git a/.github/workflows/rpi-deploy.yml b/.github/workflows/rpi-deploy.yml
--- a/.github/workflows/rpi-deploy.yml
+++ b/.github/workflows/rpi-deploy.yml
@@ -2,6 +2,19 @@ name: Build and Deploy to RPi
 
 on:
   workflow_dispatch:
+    inputs:
+      GHCR_TOKEN:
+        required: true
+        description: 'Token for GHCR'
+      RPI_HOST:
+        required: true
+        description: 'Pi host'
+      RPI_USER:
+        required: true
+        description: 'SSH user'
+      RPI_SSH_KEY:
+        required: true
+        description: 'SSH key'
   push:
     branches: [v3]
 
@@ -19,6 +32,11 @@ jobs:
         uses: docker/setup-qemu-action@v3
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
+      - name: Verify secrets
+        run: |
+          if [ -z "$GHCR_TOKEN" ] || [ -z "$RPI_HOST" ] || [ -z "$RPI_USER" ] || [ -z "$RPI_SSH_KEY" ]; then
+            echo "Missing required secrets" && exit 1
+          fi
       - name: Login to registry
         uses: docker/login-action@v3
         with:
@@ -41,5 +59,6 @@ jobs:
           username: ${{ env.RPI_USER }}
           key: ${{ env.RPI_SSH_KEY }}
           script: |
+            docker system prune -fa
             docker pull ghcr.io/${{ github.repository }}:latest
             docker compose -f /home/${{ env.RPI_USER }}/dspace/docker-compose.yml up -d app
